# Generated by Django 2.2.5 on 2019-09-16 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_c_rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={},
        ),
        migrations.AlterModelManagers(
            name='userinfo',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='menu',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_user', to='app_c_rbac.UserInfo', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='update_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_user', to='app_c_rbac.UserInfo', verbose_name='更新人'),
        ),
        migrations.AlterField(
            model_name='url',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_create_user', to='app_c_rbac.UserInfo', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='url',
            name='update_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_update_user', to='app_c_rbac.UserInfo', verbose_name='更新人'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=20, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='usertorole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_c_rbac.UserInfo', verbose_name='用户'),
        ),
    ]
