# Generated by Django 2.2.5 on 2019-09-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_c_rbac', '0002_auto_20190916_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='URL别名'),
        ),
    ]
