# Generated by Django 2.2.5 on 2019-09-16 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0002_auto_20190916_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_crm.Department', verbose_name='部门'),
        ),
    ]
